Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -25,12 +25,31 @@ jobs:
         run: |
           pip install --timeout=300 -r requirements.txt
           pip install nuitka
-          # 确保 ccache 已正确安装
           choco install ccache
+
+      - name: Install Dependency Walker
+        run: |
+          $url = "https://dependencywalker.com/depends22_x64.zip"
+          $output = "depends22_x64.zip"
+          Invoke-WebRequest -Uri $url -OutFile $output
+          Expand-Archive -Path $output -DestinationPath "C:\Tools\DependencyWalker"
+
+      - name: Set Dependency Walker Path
+        run: |
+          setx NUITKA_DEPENDS_TOOL "C:\Tools\DependencyWalker\depends.exe"
 
       - name: Build with Nuitka
         run: |
           nuitka --standalone --enable-plugin=tk-inter app.py
+
+      - name: Validate build output
+        run: |
+          if not exist app.dist\app.exe (
+            echo "Build failed: app.exe not found in app.dist" && exit 1
+          )
+
+      - name: Package build output
+        run: |
           Compress-Archive -Path app.dist\* -DestinationPath 2pdownloader-${{ env.VERSION }}-${{ matrix.architecture }}.zip
 
       - name: Upload artifacts
@@ -57,14 +76,13 @@ jobs:
         run: |
           pip install --timeout=300 -r requirements.txt
           pip install nuitka
-          # 确保 ccache 已正确安装
           brew install ccache
 
       - name: Build with Nuitka
         run: |
           nuitka --standalone --enable-plugin=tk-inter app.py
           mv app.dist 2pdownloader.app
-          chmod u+x 2pdownloader.app/app.bin # 修正路径
+          chmod u+x 2pdownloader.app/app.bin
 
       - name: Create DMG
         run: |
